const employees = [
  {
    id: 1,
    first_name: "Amit",
    email: "employee1@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Develop feature X",
        task_description: "Implement the core logic for feature X.",
        task_date: "2024-11-03",
        task_category: "Development",
      },
      {
        active: true,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Code review",
        task_description: "Review the code submitted by team members.",
        task_date: "2024-11-01",
        task_category: "Quality Assurance",
      },
      {
        active: false,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Fix bug Y",
        task_description: "Identify and resolve the issue causing bug Y.",
        task_date: "2024-10-28",
        task_category: "Bug Fixing",
      },
    ],
  },
  {
    id: 2,
    first_name: "Ravi",
    email: "employee2@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Design mockup",
        task_description: "Create a mockup for the new user dashboard.",
        task_date: "2024-11-05",
        task_category: "Design",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Meeting with client",
        task_description: "Discuss project requirements with the client.",
        task_date: "2024-11-04",
        task_category: "Client Meeting",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Prototype testing",
        task_description: "Test the prototype for feature Z.",
        task_date: "2024-10-30",
        task_category: "Testing",
      },
    ],
  },
  {
    id: 3,
    first_name: "Priya",
    email: "employee3@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Database backup",
        task_description: "Ensure all data is backed up before the update.",
        task_date: "2024-11-02",
        task_category: "Database Management",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "User research",
        task_description: "Gather feedback from users to improve UI.",
        task_date: "2024-11-06",
        task_category: "Research",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Update documentation",
        task_description: "Update user manual for the latest release.",
        task_date: "2024-10-25",
        task_category: "Documentation",
      },
    ],
  },
  {
    id: 4,
    first_name: "Neeraj",
    email: "employee4@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Organize team event",
        task_description: "Plan the details for the team-building event.",
        task_date: "2024-11-10",
        task_category: "Team Management",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "UI updates",
        task_description: "Implement UI enhancements as per feedback.",
        task_date: "2024-11-07",
        task_category: "Design",
      },
    ],
  },
  {
    id: 5,
    first_name: "Sita",
    email: "employee5@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Create API documentation",
        task_description: "Document the APIs for new features.",
        task_date: "2024-11-12",
        task_category: "Documentation",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Customer feedback call",
        task_description: "Follow up with customers for feedback.",
        task_date: "2024-11-03",
        task_category: "Customer Support",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Team meeting",
        task_description: "Review project progress with the team.",
        task_date: "2024-10-27",
        task_category: "Team Management",
      },
    ],
  },
  {
    id: 6,
    first_name: "Rahul",
    email: "employee6@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 0,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Bug triage",
        task_description: "Prioritize and assign bugs to team members.",
        task_date: "2024-11-04",
        task_category: "Bug Fixing",
      },
      {
        active: false,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Prepare presentation",
        task_description: "Create presentation for client meeting.",
        task_date: "2024-10-29",
        task_category: "Client Meeting",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Refactor codebase",
        task_description: "Improve code quality and organization.",
        task_date: "2024-11-05",
        task_category: "Development",
      },
    ],
  },
  {
    id: 7,
    first_name: "Lakshmi",
    email: "employee7@example.com",
    password: "123",
    task_counts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Optimize database",
        task_description: "Increase database performance.",
        task_date: "2024-11-08",
        task_category: "Database Management",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Design new feature",
        task_description: "Sketch out ideas for new feature implementation.",
        task_date: "2024-11-09",
        task_category: "Design",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Testing session",
        task_description: "Run tests on latest build.",
        task_date: "2024-11-02",
        task_category: "Testing",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    first_name: "Neha",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
